name: Docker Build

on:
  schedule:
    - cron: '35 4 * * 0'  # Runs on Sunday at 4:35 AM UTC
  push:
    branches: ["main"]
    tags: ['v*.*.*']

permissions:
  contents: read
  packages: write

jobs:
  docker-build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'davis-a' # Prevent builds in forks

    steps:
      - name: Publish to ghcr
        uses: e621ng/publish-to-ghcr@v1
